export const names = [
    "Sahith",
    "Arpit",
    "Aiden Wa",
    "Kaushik",
    "Aarav K",
    "Arjun C",
    "Kimson",
    "Shane",
    "Kaito",
    "Aditya S",
    "Ishaan",
    "Laksh",
    "Austin",
    "Amir",
    "Ayush R",
    "Arjun S",
    "Shikhar",
    "Arnav",
    "Anirudha",
    "Rohith",
    "William",
    "Chittresh",
    "Amato",
    "Sonia",
    "Nathan",
    "Kavya",
    "Lukas",
    "Jayden P",
    "Sohail",
    "Rithika",
    "Stephanie",
    "Prianka",
    "David Loo",
    "Rishi S",
    "Eric",
    "Haziq",
    "Aarav G",
    "Rucha",
    "Jayden M",
    "Saketh Chakravadhanula",
    "Connor",
    "Aadrika",
    "Phoebe",
    "Ansh",
    "Easton",
    "Abhiram",
    "Sammy",
    "Medha",
    "Shrinidhi",
    "Nirupa",
    "Jay",
    "Ruhaan",
    "Nikash",
    "Daxton",
    "Jash",
    "Aarav S",
    "Sean",
    "Anirudh Ram",
    "Aiden Wo",
    "Nayanika",
    "Advaith",
    "Krishay",
    "Moon",
    "Samarth",
    "Rishi T",
    "Aadit",
    "Jack",
    "Tanisha",
    "Courtney",
    "Nikhilesh",
    "Sora",
    "Hari",
    "Aaditya P",
    "Krishiv",
    "David Lin",
    "Anup",
    "Kinson",
    "Aiden Ng",
];
