name: Deploy Preview

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Install Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest

        - name: Install dependencies
          run: bun install

        - name: Build the app
          run: bun run build

        - uses: FirebaseExtended/action-hosting-deploy@v0
          with:
            repoToken: ${{ secrets.GITHUB_TOKEN }}
            firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAEL_FORCE_ROBOTICS_HF }}
            projectId: gael-force-robotics-hf
            channelId: preview
            
