name: Deploy to Firebase Hosting

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Set up Bun
          uses: oven-sh/setup-bun@v1
          with:
            bun-version: latest # or specify a version

        - name: Install dependencies
          run: bun install

        - name: Build the app
          run: bun run build

        - uses: FirebaseExtended/action-hosting-deploy@v0
          with:
            repoToken: ${{ secrets.GITHUB_TOKEN }}
            firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAEL_FORCE_ROBOTICS_HF }}
            projectId: gael-force-robotics-hf
            
